kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: auto-reply-urls
rules:
- apiGroups:
  - ""
  resources:
  - pods
  - services
  - endpoints
  - persistentvolumeclaims
  - events
  - configmaps
  - secrets
  verbs:
  - "*"
- apiGroups:
  - apps
  resources:
  - deployments
  - daemonsets
  - replicasets
  - statefulsets
  verbs:
  - "*"
- apiGroups:
  - monitoring.coreos.com
  resources:
  - servicemonitors
  verbs:
  - "get"
  - "create"
- apiGroups:
  - apps
  resources:
  - deployments/finalizers
  resourceNames:
  - auto-reply-urls
  verbs:
  - "update"
- apiGroups:
    - extensions
  resources:
    - ingresses
  verbs:
    - list
    - watch
    - get
- apiGroups:
    - "extensions"
  resources:
    - ingresses/status
  verbs:
    - update